auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("<int:pk>", views.product, name="pro"),
    path("watchlist",views.watch,name="watchlist"),
    path("cate",views.cate,name="cate"),
    path("create",views.create,name="create"),
    path("comment",views.comments,name="com"),
    path("close",views.close,name="close")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser,User
from django.db import models
from datetime import datetime,date
from django.utils import timezone


class User(AbstractUser):
    def __str__(self):
        return self.username


        
class category(models.Model):
    name = models.CharField(max_length=64)   
    def __str__(self):
        return self.name





class listing(models.Model):
    User=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    title = models.CharField(max_length=64)
    des = models.TextField()
    price = models.DecimalField(max_digits=12, decimal_places=2)
    image= models.ImageField(upload_to="photo/%y/%m/%d",blank=True,null=True)
    category=models.ForeignKey(category,on_delete=models.CASCADE,blank=True,null=True)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(default=datetime.now())
    



    def __str__(self):
        return self.title
    

class Bid(models.Model):
    User=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    listing=models.ForeignKey(listing,on_delete=models.CASCADE,blank=True,null=True)
    start = models.DecimalField(max_digits=8, decimal_places=2)
    win = models.BooleanField(default=False)
    date = models.DateTimeField(default=datetime.now())
    


    def __str__(self):
        return str(self.User)
    
class watchlist(models.Model):
    User=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    listing=models.ForeignKey(listing,on_delete=models.CASCADE,blank=True,null=True)

class comment(models.Model):
    User=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    listing=models.ForeignKey(listing,on_delete=models.CASCADE,blank=True,null=True)


    des = models.TextField()

auctions/forms.py
from django import forms
from . models import listing,Bid

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ('start',)

        
class ListingForm(forms.ModelForm):
    class Meta:
        model = listing
        exclude = ('date','active','User')
        widgets = {
            'category': forms.Select(attrs = {'class' : 'con form-control'}),
            'price': forms.NumberInput (attrs = {'class' : 'form-control'})

        }
       

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect

from django.shortcuts import render
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import login_required
from .forms import ListingForm,BidForm


from .models import User,listing,Bid,watchlist,category,comment


def index(request):
    return render(request, "auctions/index.html",
    {   
        "pro":listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")
@login_required
def product(request,pk=None):
    pro = listing.objects.get(id=pk)
    c = comment.objects.filter(listing=pro)
    print(c)
    win = Bid.objects.filter(win=True,listing=pro,User=request.user)


        


    
    if request.method == "POST":
        

        bid = request.POST["start"]
        
        if int(pro.price) >= int(bid) :

            message = "entre number more"
        else:
            message = None    
            o=listing.objects.filter(id=pk).update(price=bid)
            u =Bid(User=User.objects.get(username=request.user) ,listing=listing.objects.get(id=pk),start=bid)
            u.save()
        p = listing.objects.get(id=pk)

        return  render(request, "auctions/list.html",{
            "pro":p,
            'form':BidForm(),
            "d":p.price,
            "message":message,
            "comment":c,
            "user":request.user,
            "win":win
        })

        


    else:
        return render(request, "auctions/list.html",{
            "pro":pro,
            'form':BidForm(),
            "d":pro.price,
            "comment":c,
            "user":request.user,
            "win":win

        })


@login_required
def cate(request):
    categorys = request.GET.get('cate')
    if categorys == None:
        catey = None
    else:
        catey = listing.objects.filter(category__name=categorys)    

    
    return render(request, "auctions/cate.html",{
        'a':category.objects.all(),
        'product':catey
    })
@login_required
def watch(request):
    if request.method == 'POST':
        name=request.POST['id']
        add = watchlist(listing=listing.objects.get(pk=name),User=User.objects.get(username=request.user)).save()
        return redirect(reverse("watchlist"))

    else:
        
        return render(request, "auctions/watchlist.html",{
            'all': watchlist.objects.filter(User=User.objects.get(username=request.user))
        })    
@login_required
def create(request):
    if request.method == 'POST':
        f = ListingForm(request.POST,request.FILES)
        print(f.errors)
        if f.is_valid():
            obj = f.save(commit = False)
            obj.User=request.user
            obj.save()

        
            
        return redirect(reverse("index"))
    else:

    
        return render(request, "auctions/create.html",{
            "form":ListingForm()

        }) 


def comments(request):
    if request.method == 'POST':
        des = request.POST["comment"]
        id = request.POST["ID"]
        if des:
            i = comment(listing= listing.objects.get(pk=id), User=User.objects.get(username=request.user),des=des)
            i.save()
            return redirect(reverse("pro",args=[id]))
        else:
            return redirect(reverse("pro",args=[id]))
    


def close(request):
    b = request.POST["id2"]
    a = request.POST["id3"]
    if a:
        win = Bid.objects.filter(start=a).update(win=True)
        print(win)
    


    if b:
        q=listing.objects.filter(id=b).update(active="False")
    return redirect(reverse("pro",args=[b]))    

auctions/templates/auctions/cate.html
{% extends "auctions/layout.html" %}
{% block body %}

    {%for i in a%}
    <div class="s-list">
        
            <li class="list-group-item">
                <a href="{% url 'cate'%}?cate={{i.name}}">{{i.name}}</a>
            </li>
    </div>
    {%endfor%}
    {%for i in product %}
    <a href="{% url 'pro' i.id %}" style="color: black;   text-decoration: none;">
        <div class="cont">
            <div class="cont_image">
                    <img src="{{i.image.url}}" height="250px">
                    
            </div>
            <div class="info">
                <h4>{{i.id}}</h4>
                <h4>{{i.title}}</h4>
                <h4>Price: ${{i.price}}</h4>
                <p>{{i.date}}</p>
    
            </div>
            
    
        </div>
        </a>
    {% endfor %}


{% endblock %}  

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% load crispy_forms_tags%}
{% block body %}
    <form method="post" action="{% url 'create'%}" enctype="multipart/form-data" class="cl">
        {%csrf_token%}
        {{form|crispy}}
        <input type="submit" value="Create" class="bt">
    </form>


{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    {%for i in pro%}
    <a href="{% url 'pro' i.id %}" style="color: black;   text-decoration: none;">
    <div class="cont">
        <div class="cont_image">
                <img src="{{i.image.url}}" height="250px">
                
        </div>
        <div class="info">
            <h4>{{i.title}}</h4>
            <h4>Price:   ${{i.price}}</h4>
            <p>{{i.date}}</p>

        </div>
        

    </div>
    </a>
    {%endfor%}

   
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cate' %}">Categories</a>
                </li>

                <li class="nav-item">
    
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>

                    <li class="nav-item">

                    <a class="nav-link" href="{% url 'create' %}">Create Listing</a>
                </li>

                    <li class="nav-item">

                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/list.html
{% extends "auctions/layout.html" %}
{% load crispy_forms_tags%}


{% block body %}
    <div class="list">
        <div class="img">
            
                <img src="{{pro.image.url}}" height="400px">
              
        </div>

        <div class="cont_info">
            <div class="title">
                <h3>{{pro.title}}</h3>
                <p>{{pro.des}}</p>

            </div>
            <hr>
            <div class="price">
                <h5>current bid : <strong>${{pro.price}}</strong></h4>

            </div>
            <hr>
         
        {%if pro.active is True%}
            <div>
                <form method="post" action="{% url 'pro' pro.id %}">
                    {%csrf_token%}
                    {{form|crispy}}
                    <input type="submit" value="palce Bid" class="bt">
                </form>
            </div>
            {% if message%}
               <div>
                  <p class="alert alert-danger" style="margin-top: 4px; border-radius: 10px;">Amount entered must be higher than the current bid amount</p>

               </div>
            {%endif%}
            <div>
                <form method="post" action="{% url 'watchlist'%}">
                    {%csrf_token%}
                    <input type="hidden" value="{{pro.id}}" name="id">
                    <input type="submit" value="add cart" class="bt" style="margin-top: 4px; padding: 4px;">
                </form>    
                
            </div>
            <div>
                {%if pro.User.username == user.username%}
                <form method="post" action="{% url 'close' %}">
                    {%csrf_token%}
                    <input type="hidden" value="{{pro.price}}" name="id3">
                    <input type="hidden" value="{{pro.id}}" name="id2">
                    <input type="submit" value="close Bid" class="bt" style="margin-top: 4px; padding: 4px; background-color: red;">
                </form>
                {%endif%}                  
            </div>
        {%elif win %}
             <h3>You win The Bid</h3>    
        {%else%}    
            <h3>This Bid is close</h3>
        {%endif%} 
            
            
        </div>
        
        
         
    
        <div class="comment">
            <form class=".form-control" method="post" action="{% url 'com' %}">
                {%csrf_token%}

                <div class="form-group">
                
                <label for="id_title" class=" requiredField">
                        Comment:</label>
                <input type="text" name="comment" placeholder="Comment..." class="textinput textInput form-control" id="id_title">
                <input type="hidden" name="ID" value="{{pro.id}}">
                <input type="submit" value="Add Comment" class="bt">
                </div>
            </form>

            
            
            {%for i in comment%}
               <div class="box">
                  <p>by <span>{{i.User.username}}</span></p>
                  <hr>
                  <p>{{i.des}}</p>
                
                 
                
               </div>
            {%endfor%}
        </div>
      
        
    </div>
    



   
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% block body %}

  <ol>
   {%for i in all%}
    
    <li>
        <div class="cont">
        <div class="cont_image">
                <img src="{{i.listing.image.url}}" height="250px">
        </div>
        <div class="info">
            <h4>{{i.listing.id}}</h4>
            <h4>{{i.listing.title}}</h4>
            <h4>Price: ${{i.listing.price}}</h4>
            <p>{{i.listing.date}}</p>
            

        </div>
        

        </div>
    </li>
    {%endfor%}
  </ol>

{% endblock %}